# Generated by Django 5.0.7 on 2024-07-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Announcement title')),
                ('author', models.CharField(max_length=255, verbose_name='Announcement author')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Announcement view count')),
                ('place', models.PositiveSmallIntegerField(default=1, verbose_name='Announcement place')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
    ]
